//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_KELASI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbKelasiContainer : DbContext
    {
        public DbKelasiContainer()
            : base("name=DbKelasiContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anneAcademique> anneAcademique { get; set; }
        public virtual DbSet<classe> classe { get; set; }
        public virtual DbSet<Dossier> Dossier { get; set; }
        public virtual DbSet<etudiant> etudiant { get; set; }
        public virtual DbSet<inscrire> inscrire { get; set; }
        public virtual DbSet<Moi> Moi { get; set; }
        public virtual DbSet<Parcourscolaires> Parcourscolaires { get; set; }
        public virtual DbSet<profil> profil { get; set; }
        public virtual DbSet<regle> regle { get; set; }
        public virtual DbSet<reinscription> reinscription { get; set; }
        public virtual DbSet<tuteur> tuteur { get; set; }
    }
}
