//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_KELASI
{
    using System;
    using System.Collections.Generic;
    
    public partial class etudiant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public etudiant()
        {
            this.inscrire = new HashSet<inscrire>();
            this.regle = new HashSet<regle>();
            this.reinscription = new HashSet<reinscription>();
        }
    
        public string codeEt { get; set; }
        public string NmEt { get; set; }
        public string PrnmEt { get; set; }
        public System.DateTime DtNais { get; set; }
        public string LieuNais { get; set; }
        public string sexe { get; set; }
        public string Nationalite { get; set; }
        public string adresEt { get; set; }
        public string codeInfScol { get; set; }
        public Nullable<int> codeDo { get; set; }
        public string codeTuteur { get; set; }
    
        public virtual Dossier Dossier { get; set; }
        public virtual Parcourscolaires Parcourscolaires { get; set; }
        public virtual tuteur tuteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inscrire> inscrire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<regle> regle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reinscription> reinscription { get; set; }
    }
}
