//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_KELASI
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscrire
    {
        public string IDincription { get; set; }
        public System.DateTime dtInscription { get; set; }
        public string fraisInscription { get; set; }
        public string codeEt { get; set; }
        public Nullable<int> codeclasse { get; set; }
        public Nullable<int> codeAn { get; set; }
    
        public virtual anneAcademique anneAcademique { get; set; }
        public virtual classe classe { get; set; }
        public virtual etudiant etudiant { get; set; }
    }
}
