//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_KELASI
{
    using System;
    using System.Collections.Generic;
    
    public partial class regle
    {
        public int CodeRegle { get; set; }
        public Nullable<int> codeAn { get; set; }
        public string codeEt { get; set; }
        public Nullable<int> codeclasse { get; set; }
        public Nullable<int> codeMoi { get; set; }
    
        public virtual anneAcademique anneAcademique { get; set; }
        public virtual classe classe { get; set; }
        public virtual etudiant etudiant { get; set; }
        public virtual Moi Moi { get; set; }
    }
}
