//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_KELASI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuteur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tuteur()
        {
            this.etudiant = new HashSet<etudiant>();
        }
    
        public string codeTuteur { get; set; }
        public string NmPRPere { get; set; }
        public string NmPrMere { get; set; }
        public string AdreParent { get; set; }
        public string Tuteur1 { get; set; }
        public string NumTuteur { get; set; }
        public string lieuParent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etudiant> etudiant { get; set; }
    }
}
